### ISSUE TITLE
Addo

### ISSUE THREAD

**Issue by MaksimKayumov** [KavehYousefi/Esoteric-programming-languages#10]
Addo is self modifying, meaning that it uses code as data. And if you want to implement some other OISC, be sure to look at categories and if there is "Self-Modifying" then it means it has the same thing

**Comment by KavehYousefi** [comment]
Dear MaksimKayumov:

I thank you for your advice.

I will heed your counsel and inquire my hitherto submitted implementations with respect to the correct criteria. I remember at least one similar case where I had suspected my interpreter to not comply with the OISC and self-modification aspects, but have failed to locate the same yet.

In order for me to comprehend my Addo implementation's failure, I will limn a summary of the execution principle's tiers:

---

**(1) SOURCE CODE RESTRUCTURING:**
The source code, committed as a string, is rearranged in a one-dimensional array of integer-valued cells, the "Memory" class, which actually constitutes a sparse, mutable map or dictionary. This sparse array returns for a position not explicitly defined the default value of zero (0).

Demonstrated on an example, the input string
```
 10 5 1
  9 3 8
```
produces the following vector:
```
 memory[0] = 10
 memory[1] =  5
 memory[2] =  1
 memory[3] =  9
 memory[4] =  3
 memory[5]=  8
```
The "undefined" element at the index six (6), for example, would simulate
```
 memory[6] = 0
```
This vector, or map, is subsequently employed during the entire interpretation process, being changed by the instructions as required; the input source string is discarded.

**(2) INSTRUCTION SELECTION AND EXECUTION:**
Interpreter selects three subsequent elements from this code/data memory object — at the program's inchoation, the items `memory[0]`, `memory[1]`, and `memory[2]` —, applies the respective effects, and relocates the pointer to the new position into this array as stipulated by the `c` parameter. The restructured code, as far as comprehensible to me, would be modified through these operations.

**(3) PROGRAM TERMINATION:**
Proceeding from the lacuna of a specific termination condition, which would incorporate in any Addo program per force a perpetual repetition, I have adjudged a negative pointer location into the memory, assumed by the `a` parameter, to immediately halt the program.

---

Could you please accommodate the time to communicate to me where in this process my implementation deviates from the expected behavior?

I thank you for your efforts and apologize for my misrepresentation of the Addo programming language.

Yours faithfully,

Kaveh Yousefi

**Comment by MaksimKayumov** [comment]
Sorry, it seems that implementation is correct, and I misunderstood it because on OISC page Addo was added as not having Commands memory-mapped, and thought that implementation was wrong because of  that

**Comment by KavehYousefi** [comment]
Dear MaksimKayumov:

I thank you for your input, and will yet scrutinize my further implementations for noncompliance.

Yours faithfully,

Kaveh Yousefi
