### ISSUE TITLE
How

### ISSUE THREAD

**Issue by AtayOzgur** [KavehYousefi/Esoteric-programming-languages#4]
How can i look at the compilers

**Comment by KavehYousefi** [comment]
Dear AtayOzgur:

The preponderance among the projects comprehends all operative concepts in a single file, designated as “main.lisp”, establishing an amalgam of the lexer, parser, and actual interpreter — if extant in this formation. A compiler in its stringent definition, to my best knowledge, does not partake of my implementations, as the transformation from the esoteric provenance to its executable form targets the respective Common Lisp language implementation, ceasing before any lower level conversion.

If you desiderate, for example, the perquisition of the interpreter for the esoteric programming language “Stu”, the eponymous directory lists all available manifestations — at the time of this writing, a singular specimen — in enumerated sub-directories. Its concrete file path would thus designate https://github.com/KavehYousefi/Esoteric-programming-languages/blob/main/Stu/Stu_001/main.lisp.

The project “SOAP”, located under https://github.com/KavehYousefi/Esoteric-programming-languages/tree/main/SOAP/SOAP_001, and following a counterdistinguished pattern, imposes such convolutions as to vindicate a division into separate files; the elements “lexer.lisp”, “parser.lisp”, and “interpreter.lisp” represent the respective components for its execution. The “main.lisp” file, as a unifying principles, serves as the entry point into the execution.

If not described otherwise in the “main.lisp” file's documentation header, a project may be executed in any Common Lisp implementation, such as <i>Lispbox</i>, available under https://lispbox.common-lisp.dev/; some projects, especially such reliant on Unicode support, require more recent or potent alternatives, for instance the <i>Steel Bank Common Lisp</i> (SBCL) variant of <i>Lisp Cabinet</i>, which please see under https://sourceforge.net/projects/lispcabinet/.

I hope this answer to be apropos to your question.

Yours faithfully,

Kaveh Yousefi
