### ISSUE TITLE
Mountain language

### ISSUE THREAD

**Issue by MaksimKayumov** [KavehYousefi/Esoteric-programming-languages#7]
When I was making the language, I intended  that commands are written without spaces, but forgot to write that on a page, so can you make spaces optional?

**Comment by KavehYousefi** [comment]
Dear MaksimKayumov:

I thank you for your message.

The Common Lisp interpreter already considers whitespaces as entirely optional entities; as a corollary, their absence should not corrupt a program's execution. Any other adscititious character, however, is deprieved of such tolerance. I will adjust the examples in the source file accordingly in order to demonstrate the Mountain programming language's preference.

If you wish my implementation to banish whitespaces completely, or, alternatively, to supplement a switch for their optional admission, I supplicate a notification concerning this feature, which I would lief incorporate.

Yours faithfully,

Kaveh Yousefi
